### ISSUE TITLE
Auto Swing and Draw Guides do not work when I draw an arm or leg using only strokes.

### ISSUE THREAD

**Issue by urekmazino00** [RxLaboratory/Duik#1055] opened 2023-04-08 04:35 UTC
Auto Swing and Draw Guides do not work when I draw an arm or leg using only strokes.

https://user-images.githubusercontent.com/48952173/230703285-0061df36-c978-47b3-9fb2-2b21e103a120.mp4

**Comment by Nico-Duduf** [comment] 2023-04-08 09:30
I think it may be because it's a leg actually, and on legs the IK effect on the controller is not the actual IK effect (it's a duplicate of the one on one of the nulls created by Duik)
But that should be linked automatically by the autorig, I'll have a look
In the meantime, you can try using the settings directly on the actual IK on the corresponding null (which should be on the ankle, the name of the null should start with IK)

**Comment by urekmazino00** [comment] 2023-04-08 14:50
You're right, it didn't work because it's a leg

**Comment by Nico-Duduf** [comment] 2023-04-15 11:39
The auto-swing feature for legs is fixed in Duik 17.1 available later today;
Note that to see the guides, you'll have to enable the 'IK Foot' layer (you just have to show it, guides are drawn within this layer)

**Closed by Nico-Duduf** 2023-04-15 11:39 UTC
Labels: Bug

**Comment by urekmazino00** [comment] 2023-04-15 13:57
thanks ^^
