### ISSUE TITLE
Walkcycle not working properly

### ISSUE THREAD

**Issue by andreastanner** [RxLaboratory/Duik#973] opened 2022-12-06 14:18 UTC
Somehow, the procedural walkcycle tool is not working anymore. It works when making an OCO premade rig but when I make my own rig with bones, arms and spine, it'm getting a strange behaviour on the legs. I tried to make the rig completely new, try to use the OCO rig and make all puppet pins first to "Add pins" and link them manually. But i get the same wired movement. Maybe it's an issue with the comp size 1164px * 2380px? 

Oh and extract controllers doesn't work either. Both, the expression method and the essential properties method, the controllers are way off... 

Thanks very much for your help!

https://user-images.githubusercontent.com/55541491/205937589-dcc48825-e9aa-4817-b7df-f71b04ab9562.mp4

**Comment by Nico-Duduf** [comment] 2022-12-06 15:47
Got it thanks! I'll have a look ASAP

**Comment by andreastanner** [comment] 2022-12-06 16:22
I just found somethin out. I did the following:
1. Make a simple OCO human rig, moved the bones that the character looks in the opposite direction (left instead of right)
2. Just for testing, I made autorig, and then the walkcycle --> everything worked fine 
3. Ok, next step. The OCO rig is very small per default (btw, i doesn't need to be a oco rig, initially i made it with custom lims without OCO. The error occurs in both ways) My character is about 4K, so i made the comp size about 4000px * 2300px, it's a bit too big but it's just this test
4. I aligned the all the bones according to the characters limbs
5. I made autorig. Maybe it means nothing but the controlers are now waaaay bigger than before (maybe that sould be).
6. When i know click the walkcycle, the flipping problem occurs.

**Comment by Nico-Duduf** [comment] 2022-12-06 16:31
Here's what I've found on my side :

- For some reason, the feet rotation value goes crazy, and if you adjust that in the effect of the walk cycle it's already much better:

![image](https://user-images.githubusercontent.com/8526542/205967826-de4a7331-eec1-4ec0-bf23-8ebc4582d82c.png)

- It's still not perfect, because your rig doesn't use toes, although the walk cycle works better with them. To fix that, just remove the expressions added in the footroll (effect on the foot controller) by the walk cycle, and you'll have something much better

![image](https://user-images.githubusercontent.com/8526542/205968202-706d748e-b14b-46e4-ba6a-0138f668bfce.png)

I can't reproduce the issue with the extract controller; maybe you tried to extract them *after* applying the walk cycle?

Note: the size of the controllers is meant to be changed according to the size of the comp.
But if working in "big" comps breaks stuff like the autorig or the walk cycle, there's definitely a bug I'll have to fix, thanks for the feedback

**Comment by andreastanner** [comment] 2022-12-06 19:01
Thank you very much Nicolas! That really helped for a quick fix. I will make a proper foot with toes like you suggested. Anyway, thanks for looking into the problem regarding big comps. Your fast reply's on problems is one reason why i personally and our office support your work!!

**Comment by Nico-Duduf** [comment] 2023-02-09 14:09
fixed in 17.0.2

**Closed by Nico-Duduf** 2023-02-09 14:09 UTC
Labels: Bug
