### ISSUE TITLE
Changing settings and applying them prompts an error message

### ISSUE THREAD

**Issue by reneandritsch** [RxLaboratory/Duik#916] opened 2022-05-19 13:41 UTC
**Describe the bug**
When changing the DUIK settings and applying them After Effects prompts an error message

**To Reproduce**
1. Open Settings dialogue
2. Change for instance UI mode
3. Hit Apply

**Error description, if any**
Error message: See screenshot. This window appears twice.

**Expected behavior**
No error should show up

**Screenshots**
![duik-settings](https://user-images.githubusercontent.com/38455050/169307197-b93a5957-9de6-4fe4-bcaa-bd0536d908ea.png)

![duik-settings-error](https://user-images.githubusercontent.com/38455050/169307665-2e184934-7a06-490b-8794-b5d070226683.png)

**System (please complete the following information):**
 - OS: macOS 12.3.1
 - Version of After Effects: 22.3.0
 - Version of Duik: DUIK Angela 17.0.0-Beta1

**Comment by Nico-Duduf** [comment] 2022-05-23 08:54
Yes that looks like a bug in After Effects; it's random, it doesn't happen at each time, and I never found the cause unfortunately... I'm closing the issue, but I'm still searching a workaround ;)

**Closed by Nico-Duduf** 2022-05-23 08:54 UTC
Labels: Bug
