### ISSUE TITLE
Options for where Duik creates it's folders

### ISSUE THREAD

**Issue by Morganimator** [RxLaboratory/Duik#898] opened 2022-04-13 18:56 UTC
**Is your feature request related to a problem? Please describe.**
In the Mac labs at our college, all user accounts' "Documents" folders are redirected to a network (I know, it's pretty weird), with one of the recent updates to the Mac OS, this has made it so we can't run Duik (regardless of whether it is installed or we try and run it manually) in **any** of our Mac labs. It's a huge bummer!

**Describe the solution you'd like**
This is what our College's IT person said:
"If the plugin can use the local Users library, such as the path "/Users/username/Library", that would stay local to each computer the student logs into, and would greatly improve the performance for the plugin to work with our lab environment. If this path can't be defined, if it is possible to prompt the user where these folders should be created, that would be an option as well."

**Describe alternatives you've considered**
I think the above quote suggests two options. I guess another option is would be for us to find someone to alter Duik (since it's open-source). I asked, but no one in our IT department is willing, so I guess I'd have to find someone capable of doing that (I'm certainly not).

Thanks for considering!
M

**Comment by Nico-Duduf** [comment] 2022-04-15 10:17
Hi Morgan,

I'm sorry for these issues. I'll give you a couple of scripts later today to run some tests on one of these macs and check what can be done to avoid this issue in future versions of Duik,
And to fix the problem right now I'll also give you a little script made to manually change the path used by Duik.

The problem is that Duik uses the user's folder, and relies on After Effects to get its path; so I can't easily detect if this path is wrong or special to automatically fix the issue/choose a better folder in this specific case... I'll think about a workaround...

**Comment by Morganimator** [comment] 2022-04-15 11:53
Thank you so much for looking at this!

And absolutely no need for you to apologize.

The problem is **clearly** our weird institution and the strange way they've set up the network. One of the IT guys - who is relatively new - said he's worked at several colleges and has **never** seen one set up this way and doesn't really understand why it was set up this way. But he's just a junior member of the IT department and made it clear that it's been this way for over a decade and no one's going to change it now. Especially not just for one lowly faculty member with one tech problem.

So I really appreciate your help! I just ran out of options trying to solve it here.

**Comment by Nico-Duduf** [comment] 2022-04-15 13:45
I understand that ;) School often have weird setups like this...

Can you run this script on one of the mac using After Effects and post the result here please?
[DuSI.zip](https://github.com/RxLaboratory/DuAEF_Duik/files/8496200/DuSI.zip)

It will ask for a location to save some system information, then you can just copy the content of the file here.
Thanks!

**Comment by Morganimator** [comment] 2022-04-15 14:34
Sure thing. I'm heading to school in a bit and I'll be able to run it this afternoon.
Thank you!

**Comment by Nico-Duduf** [comment] 2022-04-15 15:32
[setBasselSettingsFile.zip](https://github.com/RxLaboratory/DuAEF_Duik/files/8496727/setBasselSettingsFile.zip)

This is a script which should fix the issue: just run it in After Effects. It'll ask for a new location for the settings file used by Duik, you can set anything you wish. My advice is to set it in an dedicated empty folder, as Duik will also extract there some other files it needs.
Then, just restart Duik and it *may* work correctly.

Depending on the weird configuration of the computers, maybe there will still be some issues as Duik extracts other files in another folder (the icons and the effects); this one will be a more difficult to fix if there are some issues, but we'll see, just let me know

**Comment by Morganimator** [comment] 2022-04-15 22:09
Hi Nicolas,

The first script, DuSI.jsx would not run. I'll attach the error message I got trying to run that.

I was able to run the second "setBasselSettingsFile.jsx script and chose a local folder on the scratch, but I got the same error message we've been getting when trying to run Duik.

Again, I really appreciate you taking your valuable time to look into this. And regardless of whether or not we can solve this issue, my boss, the head of the Department of Motion Design, plans to send a donation to Rainbox from the department's budget to thank you for your time and trouble!

![Screen Shot 2022-04-15 at 5 56 06 PM](https://user-images.githubusercontent.com/74509994/163647566-86172337-c7de-4d31-bff5-198e75439b50.png)
![Screen Shot 2022-04-15 at 6 01 07 PM](https://user-images.githubusercontent.com/74509994/163647573-29cf2d21-51d7-44e7-bc2b-17eac29bee52.png)
!

**Comment by Nico-Duduf** [comment] 2022-04-16 16:44
It seems to be worse than I thought!

If Duik complains about image data, that means it's the icons it can't access correctly, and that's a more difficult issue to fix, but we'll know more when DuSI will work to collect more info.

Here's an update of of DuSI which should work better, it seems something really weird is going on on these Macs
[DuSI_V1.1.zip](https://github.com/RxLaboratory/Duik/files/8500306/DuSI_V1.1.zip)

Can you also check manually the `/Library/Application Support` Folder? check if it exists and what's in it. and if there's any redirection there...
If you find any folder called `DuAEF` in there, just delete it, that may also help Duik if some files are corrupted there!

**Comment by Morganimator** [comment] 2022-04-19 20:13
I'm not at all surprised that something really weird is going on. This whole campus is really weird - especially the IT department which is a mess...🙃

- There is a /Library/Application Support folder that seems to be local. I'm not sure how to tell if it's redirected...? I'll attach a screen shot. There was no DuAEF folder in there.
- The DuSI script worked. I've attached the file it created.

Thanks so much!
[DuSIResult.zip](https://github.com/RxLaboratory/Duik/files/8516195/DuSIResult.zip)
![Screen Shot 2022-04-19 at 4 11 54 PM](https://user-images.githubusercontent.com/74509994/164087866-fe95e819-62d4-45e0-9074-1d444d694cb0.png)

**Comment by Nico-Duduf** [comment] 2022-04-26 18:42
Okay so I may have a solution.

First, here's a new version of DuSI just to check everything goes as I expect; you just have to run it again and post the result here as you did before.
[DuSI_v1.2.1.zip](https://github.com/RxLaboratory/Duik/files/8565987/DuSI_v1.2.1.zip)

And then you can try with Duik Ángela, a custom version just for you ;) If it works, that's good news it means all future versions of if should work too, so you can safely update it later. You should already be able to use it with your students, it will be released as a public beta very soon and almost all features are available already.
[Duik Angela_vMorgan.zip](https://github.com/RxLaboratory/Duik/files/8565992/Duik.Angela_vMorgan.zip)

Let me know if that works. If not, at least we're closing to a solution, I promise ;)

**Comment by Morganimator** [comment] 2022-04-27 17:22
Thank you so much, Nicolas!

I'm not on campus today. But I will try these scripts tomorrow and let you know the results.

I so appreciate your willingness to help me and my students!

Best,
M

**Comment by Morganimator** [comment] 2022-04-28 15:04
Yay! I got it to work. However, when I first ran the Angela script, it froze both Duik and Ae after I chose a language. But then I quit and restarted Ae and re-ran it and it worked!

I also ran the DuSI script and I've attached the results.

Thank you again so much! It looks like this solution will work...

[DuSIResults_4.28.zip](https://github.com/RxLaboratory/Duik/files/8583919/DuSIResults_4.28.zip)
!

**Comment by Nico-Duduf** [comment] 2022-04-29 10:22
Thanks for your feedback. That confirms the issue: on this system there's no available standard folder for After Effects scripts to store their stuff; the only available folders with write access are your documents and desktop, which is not a right place to extract a big bunch of effect files and icons. Fortunately, there's also a write access to a temporary folder, that's the workaround I implemented; the issue with that is that all these assets will be deleted by the OS from time to time, so Duik will have to extract them again, that will make it a bit longer to load. Not a big problem though!
Thanks!

**Closed by Nico-Duduf** 2022-04-29 10:22 UTC
Labels: Enhancement, WIP
